package dynastyGUI;

import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollBar;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

public class DynastyGUI extends JFrame {
	/**
	 * Autogenerated serial version UID
	 */
	private static final long serialVersionUID = -930754539549539445L;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		// Call the init method to begin the GUI
		init();
	}

	/**
	 * Create the frame.
	 */
	public DynastyGUI() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 300);
		loginPanel();
	}
	
	public static void init() {
		/*
		 * Method that starts the GUI inside the EventQueue Thread
		 */
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					DynastyGUI frame = new DynastyGUI();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}
	
	public void updatePane(JPanel panel) {
		getContentPane().add(panel);
		getContentPane().doLayout();
		update(getGraphics());
	}
	
	public void loginPanel() {
		JPanel loginPanel = new JPanel();
		loginPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		loginPanel.setLayout(null);
		getContentPane().removeAll();
		
		JLabel title = new JLabel("Dynasty Cars Inventory System");
		title.setFont(new Font("Tahoma", Font.PLAIN, 20));
		title.setBounds(70, 11, 294, 42);
		loginPanel.add(title);
		
		JLabel loginLabel = new JLabel("Login");
		loginLabel.setFont(new Font("Tahoma", Font.PLAIN, 15));
		loginLabel.setBounds(194, 60, 46, 19);
		loginPanel.add(loginLabel);
		
		JLabel usernameLabel = new JLabel("Username");
		usernameLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
		usernameLabel.setBounds(234, 91, 68, 14);
		loginPanel.add(usernameLabel);
		
		JLabel passwordLabel = new JLabel("Password");
		passwordLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
		passwordLabel.setBounds(234, 116, 68, 14);
		loginPanel.add(passwordLabel);
		
		JTextField usernameBox = new JTextField();
		usernameBox.setBounds(319, 90, 86, 20);
		usernameBox.setColumns(10);
		loginPanel.add(usernameBox);
		
		JPasswordField passwordBox = new JPasswordField();
		passwordBox.setColumns(10);
		passwordBox.setBounds(319, 115, 86, 20);
		passwordBox.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				String uname = usernameBox.getText();
				String pword = String.valueOf(passwordBox.getPassword());
				
				if(uname.equals("admin") && pword.equals("password")) {
					JOptionPane.showMessageDialog(getContentPane(), "Admin Logged in Succesfully");
					menuAdminPanel();
				}else
				{
					JOptionPane.showMessageDialog(getContentPane(), "Incorrect username or password. Please try again.");
				}
			}
		});
		loginPanel.add(passwordBox);
		
		JButton adminLoginButton = new JButton("Enter");
		adminLoginButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				String uname = usernameBox.getText();
				String pword = String.valueOf(passwordBox.getPassword());
				
				if(uname.equals("admin") && pword.equals("password")) {
					JOptionPane.showMessageDialog(getContentPane(), "Admin Logged in Succesfully");
					menuAdminPanel();
				}else
				{
					JOptionPane.showMessageDialog(getContentPane(), "Incorrect username or password. Please try again.");
				}
			}
		});
		adminLoginButton.setBounds(256, 141, 89, 23);
		loginPanel.add(adminLoginButton);
		
		JLabel guestLabel = new JLabel("Guest Login");
		guestLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
		guestLabel.setBounds(70, 90, 75, 17);
		loginPanel.add(guestLabel);
		
		JButton guestLoginButton = new JButton("Enter");
		guestLoginButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				searchPanel();
			}
		});
		guestLoginButton.setBounds(66, 141, 89, 23);
		loginPanel.add(guestLoginButton);
		
		updatePane(loginPanel);
	}
	
	public void searchPanel() {
		JPanel searchPanel = new JPanel();
		searchPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		searchPanel.setLayout(null);
		getContentPane().removeAll();
		
		JLabel lblSearch = new JLabel("Search");
		lblSearch.setFont(new Font("Tahoma", Font.PLAIN, 20));
		lblSearch.setBounds(187, 11, 60, 37);
		searchPanel.add(lblSearch);
		
		JLabel lblNewLabel = new JLabel("Enter Search Parameters:");
		lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 12));
		lblNewLabel.setBounds(68, 68, 140, 14);
		searchPanel.add(lblNewLabel);
		
		String[] color = {"Color", "Blue", "Red", "Green"};
		String[] brand = {"Brand", "Toyota", "Dodge", "Ram"};
		String[] type = {"Type", "SUV", "Truck", "Coupe"};
		String[] MPG = {"MPG", "70-45", "44-35", "34-25", "24-10"};
		String[] convert = {"Convertible", "Yes", "No"};
		String[] fuel = {"Fuel type", "Gasoline", "Diesel"};
		
		JComboBox<String> colorBox = new JComboBox<String>(color);
		colorBox.setToolTipText("Color");
		colorBox.setBounds(260, 124, 86, 20);
		searchPanel.add(colorBox);
		
		JComboBox<String> brandBox = new JComboBox<String>(brand);
		brandBox.setToolTipText("Brand");
		brandBox.setBounds(68, 93, 86, 20);
		searchPanel.add(brandBox);
		
		JComboBox<String> typeBox = new JComboBox<String>(type);
		typeBox.setToolTipText("Type");
		typeBox.setBounds(164, 93, 86, 20);
		searchPanel.add(typeBox);
		
		JComboBox<String> convertBox = new JComboBox<String>(convert);
		convertBox.setToolTipText("Convertible");
		convertBox.setBounds(164, 124, 86, 20);
		searchPanel.add(convertBox);
		
		JComboBox<String> fuelBox = new JComboBox<String>(fuel);
		fuelBox.setToolTipText("Fuel Type");
		fuelBox.setBounds(68, 124, 86, 20);
		searchPanel.add(fuelBox);
		
		JComboBox<String> MPGBox = new JComboBox<String>(MPG);
		MPGBox.setToolTipText("MPG");
		MPGBox.setBounds(260, 93, 86, 20);
		searchPanel.add(MPGBox);
		
		JButton findBtn = new JButton("Find");
		findBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				//Access database to perform search function
				JOptionPane.showMessageDialog(getContentPane(), "Searching Database for the Perfect Vehicle");
				searchDisplayPanel();
			}
		});
		findBtn.setBounds(161, 169, 89, 23);
		add(findBtn);
		
		JButton button = new JButton("Logout");
		button.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				loginPanel();
			}
		});
		button.setBounds(10, 227, 86, 23);
		searchPanel.add(button);
		
		updatePane(searchPanel);
	}
	
	public void menuAdminPanel() {
		JPanel menuAdmin = new JPanel();
		menuAdmin.setBorder(new EmptyBorder(5, 5, 5, 5));
		menuAdmin.setLayout(null);
		getContentPane().removeAll();
		
		JLabel lblMainMenu = new JLabel("Main Menu");
		lblMainMenu.setFont(new Font("Tahoma", Font.PLAIN, 20));
		lblMainMenu.setBounds(169, 11, 96, 37);
		menuAdmin.add(lblMainMenu);
		
		JLabel searchLabel = new JLabel("Search");
		searchLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
		searchLabel.setBounds(66, 75, 142, 17);
		menuAdmin.add(searchLabel);
		
		JLabel lblDisplayTotalInventory = new JLabel("Display Total Inventory");
		lblDisplayTotalInventory.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblDisplayTotalInventory.setBounds(66, 100, 142, 17);
		menuAdmin.add(lblDisplayTotalInventory);
		
		JLabel lblLogOut = new JLabel("Log Out");
		lblLogOut.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblLogOut.setBounds(66, 125, 142, 17);
		menuAdmin.add(lblLogOut);
		
		JLabel lblExit = new JLabel("Exit");
		lblExit.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblExit.setBounds(66, 150, 142, 17);
		menuAdmin.add(lblExit);
		
		JButton searchBtn = new JButton("Go");
		searchBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				searchAdminPanel();
			}
		});
		searchBtn.setBounds(246, 74, 89, 23);
		menuAdmin.add(searchBtn);
		
		JButton displayBtn = new JButton("Go");
		displayBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				displayAdminPanel();
			}
		});
		displayBtn.setBounds(246, 99, 89, 23);
		menuAdmin.add(displayBtn);
		
		JButton logOutBtn = new JButton("Go");
		logOutBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				JOptionPane.showMessageDialog(getContentPane(), "Logging out");
				loginPanel();
			}
		});
		logOutBtn.setBounds(246, 124, 89, 23);
		menuAdmin.add(logOutBtn);
		
		JButton exitBtn = new JButton("Go");
		exitBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				JOptionPane.showMessageDialog(getContentPane(), "Closing Program");
				System.exit(0);
			}
		});
		exitBtn.setBounds(246, 149, 89, 23);
		menuAdmin.add(exitBtn);
		
		JLabel lblNewLabel = new JLabel("Admin Controls");
		lblNewLabel.setBounds(10, 11, 96, 14);
		menuAdmin.add(lblNewLabel);
		
		updatePane(menuAdmin);
	}
	
	public void searchDisplayPanel() {
		JPanel searchDisplayPanel = new JPanel();
		searchDisplayPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		searchDisplayPanel.setLayout(null);
		getContentPane().removeAll();
		
		JLabel lblNewLabel = new JLabel("Cars Found");
		lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 20));
		lblNewLabel.setBounds(170, 24, 99, 19);
		searchDisplayPanel.add(lblNewLabel);
		
		JLabel lblNewLabel_1 = new JLabel("Somehow displaying data collected from database...");
		lblNewLabel_1.setBounds(74, 98, 334, 29);
		searchDisplayPanel.add(lblNewLabel_1);
		
		JButton newSearchBtn = new JButton("New Search");
		newSearchBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				searchPanel();
			}
		});
		newSearchBtn.setBounds(303, 209, 105, 29);
		searchDisplayPanel.add(newSearchBtn);
		
		updatePane(searchDisplayPanel);
	}
	
	public void searchAdminPanel() {
		JPanel searchAdminPanel = new JPanel();
		searchAdminPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		searchAdminPanel.setLayout(null);
		getContentPane().removeAll();
		
		
		JLabel lblSearch = new JLabel("Search");
		lblSearch.setFont(new Font("Tahoma", Font.PLAIN, 20));
		lblSearch.setBounds(187, 11, 60, 37);
		searchAdminPanel.add(lblSearch);
		
		JLabel lblNewLabel = new JLabel("Enter Search Parameters:");
		lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 12));
		lblNewLabel.setBounds(68, 68, 140, 14);
		searchAdminPanel.add(lblNewLabel);
		
		String[] color = {"Color", "Blue", "Red", "Green"};
		String[] brand = {"Brand", "Toyota", "Dodge", "Ram"};
		String[] type = {"Type", "SUV", "Truck", "Coupe"};
		String[] MPG = {"MPG", "70-45", "44-35", "34-25", "24-10"};
		String[] convert = {"Convertible", "Yes", "No"};
		String[] fuel = {"Fuel type", "Gasoline", "Diesel"};
		
		JComboBox<String> colorBox = new JComboBox<String>(color);
		colorBox.setToolTipText("Color");
		colorBox.setBounds(260, 124, 86, 20);
		searchAdminPanel.add(colorBox);
		
		JComboBox<String> brandBox = new JComboBox<String>(brand);
		brandBox.setToolTipText("Brand");
		brandBox.setBounds(68, 93, 86, 20);
		searchAdminPanel.add(brandBox);
		
		JComboBox<String> typeBox = new JComboBox<String>(type);
		typeBox.setToolTipText("Type");
		typeBox.setBounds(164, 93, 86, 20);
		searchAdminPanel.add(typeBox);
		
		JComboBox<String> convertBox = new JComboBox<String>(convert);
		convertBox.setToolTipText("Convertible");
		convertBox.setBounds(164, 124, 86, 20);
		searchAdminPanel.add(convertBox);
		
		JComboBox<String> fuelBox = new JComboBox<String>(fuel);
		fuelBox.setToolTipText("Fuel Type");
		fuelBox.setBounds(68, 124, 86, 20);
		searchAdminPanel.add(fuelBox);
		
		JComboBox<String> MPGBox = new JComboBox<String>(MPG);
		MPGBox.setToolTipText("MPG");
		MPGBox.setBounds(260, 93, 86, 20);
		searchAdminPanel.add(MPGBox);
		
		JButton findBtn = new JButton("Find");
		findBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				//Access database to perform search function
				JOptionPane.showMessageDialog(getContentPane(), "Searching Database for the Perfect Vehicle");
				searchDisplayAdminPanel();
			}
		});
		findBtn.setBounds(161, 169, 89, 23);
		searchAdminPanel.add(findBtn);
		
		JButton backMenuBtn = new JButton("Back");
		backMenuBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				menuAdminPanel();
			}
		});
		backMenuBtn.setBounds(10, 227, 86, 23);
		searchAdminPanel.add(backMenuBtn);
		
		JLabel label = new JLabel("Admin Controls");
		label.setBounds(10, 11, 96, 14);
		searchAdminPanel.add(label);
		
		JButton btnSearchHistory = new JButton("Search History");
		btnSearchHistory.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				historyAdminPanel();
			}
		});
		btnSearchHistory.setBounds(10, 186, 118, 30);
		searchAdminPanel.add(btnSearchHistory);
		
		updatePane(searchAdminPanel);
	}
	
	public void displayAdminPanel() {
		JPanel displayAdminPanel = new JPanel();
		displayAdminPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		displayAdminPanel.setLayout(null);
		getContentPane().removeAll();
		
		JLabel displayAll = new JLabel("Somehow collect and display all data from database");
		displayAll.setBounds(86, 117, 315, 14);
		displayAdminPanel.add(displayAll);
		
		JLabel totalInventory = new JLabel("Entire Inventory");
		totalInventory.setFont(new Font("Tahoma", Font.PLAIN, 20));
		totalInventory.setBounds(146, 24, 143, 25);
		displayAdminPanel.add(totalInventory);
		
		JButton backBtn = new JButton("Back");
		backBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				menuAdminPanel();
			}
		});
		backBtn.setBounds(10, 227, 89, 23);
		displayAdminPanel.add(backBtn);
		
		JLabel label = new JLabel("Admin Controls");
		label.setBounds(10, 11, 96, 14);
		displayAdminPanel.add(label);
		
		updatePane(displayAdminPanel);
	}
	
	public void searchDisplayAdminPanel() {
		JPanel searchDisplayAdminPanel = new JPanel();
		searchDisplayAdminPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		searchDisplayAdminPanel.setLayout(null);
		getContentPane().removeAll();
		
		
		JLabel lblNewLabel = new JLabel("Cars Found");
		lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 20));
		lblNewLabel.setBounds(170, 24, 99, 19);
		searchDisplayAdminPanel.add(lblNewLabel);
		
		JLabel lblNewLabel_1 = new JLabel("Somehow displaying data collected from database...");
		lblNewLabel_1.setBounds(74, 98, 334, 29);
		searchDisplayAdminPanel.add(lblNewLabel_1);
		
		JButton newSearchBtn = new JButton("New Search");
		newSearchBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				searchAdminPanel();
			}
		});
		newSearchBtn.setBounds(303, 209, 105, 29);
		searchDisplayAdminPanel.add(newSearchBtn);
		
		JLabel label = new JLabel("Admin Controls");
		label.setBounds(10, 11, 96, 14);
		searchDisplayAdminPanel.add(label);
		
		updatePane(searchDisplayAdminPanel);
	}
	
	public void historyAdminPanel() {
		JPanel historyAdminPanel = new JPanel();
		historyAdminPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		historyAdminPanel.setLayout(null);
		getContentPane().removeAll();
		
		JLabel lblUserSearchHistory = new JLabel("User Search History");
		lblUserSearchHistory.setFont(new Font("Tahoma", Font.PLAIN, 20));
		lblUserSearchHistory.setBounds(130, 22, 175, 25);
		historyAdminPanel.add(lblUserSearchHistory);
		
		JLabel label = new JLabel("Admin Controls");
		label.setBounds(10, 11, 96, 14);
		historyAdminPanel.add(label);
		
		JScrollBar scrollBar = new JScrollBar();
		scrollBar.addAdjustmentListener(new AdjustmentListener() {
			public void adjustmentValueChanged(AdjustmentEvent e) 
			{
				//label.setText("This is some infoooo");
			}
		});
		scrollBar.setBounds(365, 115, 17, 65);
		historyAdminPanel.add(scrollBar);
		
		JLabel textBoxFull = new JLabel("Ford ,Truck, Black, 25MPG, non-convertible");
		textBoxFull.setBounds(97, 115, 258, 25);
		historyAdminPanel.add(textBoxFull);
		
		JLabel lblRamCoupeRed = new JLabel("RAM, Coupe, Red, 28MPG, convertible");
		lblRamCoupeRed.setBounds(97, 139, 258, 25);
		historyAdminPanel.add(lblRamCoupeRed);
		
		JLabel lblToyotaSuvWhite = new JLabel("Toyota, SUV, White, 32MPG, non-convertible");
		lblToyotaSuvWhite.setBounds(97, 161, 258, 25);
		historyAdminPanel.add(lblToyotaSuvWhite);
		
		JButton button = new JButton("Back");
		button.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				menuAdminPanel();
			}
		});
		button.setBounds(10, 227, 89, 23);
		historyAdminPanel.add(button);
		
		updatePane(historyAdminPanel);
	}
	
	public void displayPanel() {
		JPanel displayPanel = new JPanel();
		displayPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		displayPanel.setLayout(null);
		getContentPane().removeAll();
		
		JLabel displayAll = new JLabel("Somehow collect and display all data from database");
		displayAll.setBounds(86, 117, 315, 14);
		displayPanel.add(displayAll);
		
		JLabel totalInventory = new JLabel("Entire Inventory");
		totalInventory.setFont(new Font("Tahoma", Font.PLAIN, 20));
		totalInventory.setBounds(146, 24, 143, 25);
		displayPanel.add(totalInventory);
		
		JButton backBtn = new JButton("Back");
		backBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				menuPanel();
			}
		});
		backBtn.setBounds(10, 227, 89, 23);
		displayPanel.add(backBtn);
		
		updatePane(displayPanel);
	}
	
	public void menuPanel() {
		JPanel menuPanel = new JPanel();
		menuPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		menuPanel.setLayout(null);
		getContentPane().removeAll();
		
		JLabel lblMainMenu = new JLabel("Main Menu");
		lblMainMenu.setFont(new Font("Tahoma", Font.PLAIN, 20));
		lblMainMenu.setBounds(169, 11, 96, 37);
		menuPanel.add(lblMainMenu);
		
		JLabel searchLabel = new JLabel("Search");
		searchLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
		searchLabel.setBounds(66, 75, 142, 17);
		menuPanel.add(searchLabel);
		
		JLabel lblDisplayTotalInventory = new JLabel("Display Total Inventory");
		lblDisplayTotalInventory.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblDisplayTotalInventory.setBounds(66, 100, 142, 17);
		menuPanel.add(lblDisplayTotalInventory);
		
		JLabel lblLogOut = new JLabel("Log Out");
		lblLogOut.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblLogOut.setBounds(66, 125, 142, 17);
		menuPanel.add(lblLogOut);
		
		JLabel lblExit = new JLabel("Exit");
		lblExit.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblExit.setBounds(66, 150, 142, 17);
		menuPanel.add(lblExit);
		
		JButton searchBtn = new JButton("Go");
		searchBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				searchPanel();
			}
		});
		searchBtn.setBounds(246, 74, 89, 23);
		menuPanel.add(searchBtn);
		
		JButton displayBtn = new JButton("Go");
		displayBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				displayPanel();
			}
		});
		displayBtn.setBounds(246, 99, 89, 23);
		menuPanel.add(displayBtn);
		
		JButton logOutBtn = new JButton("Go");
		logOutBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				JOptionPane.showMessageDialog(getContentPane(), "Logging out");
				//doesn't work. Not sure why. Error on setVisible
				loginPanel();
			}
		});
		logOutBtn.setBounds(246, 124, 89, 23);
		menuPanel.add(logOutBtn);
		
		JButton exitBtn = new JButton("Go");
		exitBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) 
			{
				JOptionPane.showMessageDialog(getContentPane(), "Closing Program");
				System.exit(0);
			}
		});
		exitBtn.setBounds(246, 149, 89, 23);
		menuPanel.add(exitBtn);
		
		updatePane(menuPanel);
	}
}
